---
# tasks file for ansible-role-docker
- import_tasks: configure.yml
- import_tasks: debian.yml
  when: ansible_facts['distribution']|lower == "debian"
- import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == "ubuntu"
- name: Enable systemd service
  systemd:
    name: "docker.service"
    state: started
    enabled: yes
- name: Test Docker with hello world example
  command: "docker run --rm hello-world"
  changed_when: false
- name: Install Docker Python module
  pip:
    name: docker
